"""Seed Firestore with the crops collection -- the data backbone (PROJECT_SPEC.md).

This single crops/{crop_id} collection feeds four things:
  - crop recommendations (match soil_types / seasons / regions),
  - the diagnosis prior and community-alert crop filter (susceptible_diseases),
  - reminders (cycle_days + growth_stages).

Uses fixed document ids and `.set()` (full overwrite) via upsert_crop, so running
this twice leaves Firestore in the same state (idempotent).

Detail level:
  - Rich, agronomically accurate: the demo crops (tomato, rice, groundnut, cotton).
  - Reasonable: the remaining common Indian crops.

Conventions:
  - soil_types use the spec tokens: black | red | alluvial | loam | sandy | clay.
  - regions use agro-climatic-zone tokens that line up with the recommend form's
    "area" chips (delta, coastal, upland, semi_arid) plus arid / hilly / irrigated.
  - susceptible_diseases are condition ids (snake_case). nitrogen_deficiency is a
    condition but NOT a disease, so it never appears here.
"""
from firestore_client import upsert_crop
from models import Crop, CropNames, GrowthStage


def _stage(name, start_day, care_note):
    return GrowthStage(name=name, start_day=start_day, care_note=care_note)


CROPS = [
    # ---- Demo crops: rich, accurate detail ---------------------------------
    Crop(
        id="tomato",
        names=CropNames(en="Tomato", hi="टमाटर", te="టమాటా"),
        seasons=["kharif", "rabi", "zaid"],
        soil_types=["black", "red", "loam", "alluvial"],
        water_need="medium",
        regions=["coastal", "delta", "upland", "semi_arid"],
        cycle_days=120,
        growth_stages=[
            _stage("nursery", 0, "Raise healthy seedlings in a shaded, well-drained bed; keep soil moist, not wet."),
            _stage("transplanting", 25, "Transplant sturdy 25-30 day seedlings in the evening; water in immediately."),
            _stage("vegetative", 35, "Weed early and stake plants; watch lower leaves for the first dark spots."),
            _stage("flowering", 55, "Keep moisture steady to prevent flower drop; avoid overhead watering that wets leaves."),
            _stage("fruiting", 75, "Support heavy trusses; harvest firm ripe fruit regularly to keep plants productive."),
            _stage("harvest", 100, "Pick every 2-3 days; remove any blighted fruit and leaves away from the field."),
        ],
        # late blight and early blight are the tomato conditions the fusion prior covers.
        susceptible_diseases=["late_blight", "early_blight"],
    ),
    Crop(
        id="rice",
        names=CropNames(en="Rice", hi="धान", te="వరి"),
        seasons=["kharif", "rabi"],
        soil_types=["alluvial", "clay", "loam", "black"],
        water_need="high",
        regions=["delta", "coastal", "irrigated"],
        cycle_days=135,
        growth_stages=[
            _stage("nursery", 0, "Sow in a puddled, well-levelled nursery; keep a thin film of water."),
            _stage("transplanting", 25, "Transplant 2-3 seedlings per hill at 20x15 cm; keep 2-3 cm standing water."),
            _stage("tillering", 40, "Maintain shallow water and top-dress nitrogen; keep the field weed-free."),
            _stage("panicle_initiation", 65, "Do not let the field dry now; this stage decides grain number."),
            _stage("flowering", 90, "Keep steady water; avoid stress and watch for stem borer and blast."),
            _stage("grain_filling", 105, "Drain gently near maturity to firm the crop for harvest."),
            _stage("maturity", 125, "Harvest at 80-85% golden grains; dry promptly to avoid grain loss."),
        ],
        susceptible_diseases=["rice_blast", "bacterial_leaf_blight", "sheath_blight"],
    ),
    Crop(
        id="groundnut",
        names=CropNames(en="Groundnut", hi="मूंगफली", te="వేరుశనగ"),
        seasons=["kharif", "rabi"],
        soil_types=["red", "sandy", "loam"],
        water_need="low",
        regions=["semi_arid", "upland", "coastal"],
        cycle_days=110,
        growth_stages=[
            _stage("germination", 0, "Sow in warm, well-drained soil; ensure gypsum and good seed treatment."),
            _stage("vegetative", 20, "Keep weed-free; light, frequent moisture beats heavy irrigation."),
            _stage("flowering_pegging", 40, "Critical for yield -- do not let soil dry; apply gypsum at pegging."),
            _stage("pod_development", 65, "Maintain even moisture so pods fill; watch for leaf spot and rust."),
            _stage("maturity", 95, "Check inner shell colour; harvest before pods over-mature and detach."),
        ],
        susceptible_diseases=["tikka_leaf_spot", "rust", "collar_rot"],
    ),
    Crop(
        id="cotton",
        names=CropNames(en="Cotton", hi="कपास", te="పత్తి"),
        seasons=["kharif"],
        soil_types=["black", "red", "loam"],
        water_need="medium",
        regions=["semi_arid", "upland", "coastal"],
        cycle_days=170,
        growth_stages=[
            _stage("germination", 0, "Sow with the onset of monsoon into moist soil; ensure a good, even stand."),
            _stage("squaring", 40, "Keep weed-free and scout for sucking pests; avoid excess nitrogen."),
            _stage("flowering", 70, "Peak water need -- keep moisture steady; monitor for bollworm."),
            _stage("boll_development", 100, "Maintain moisture so bolls fill; continue pest scouting."),
            _stage("boll_opening", 140, "Reduce water as bolls open; pick clean cotton in dry weather."),
        ],
        susceptible_diseases=["bacterial_blight", "leaf_curl_virus", "fusarium_wilt"],
    ),
    # ---- Other common Indian crops: reasonable detail ----------------------
    Crop(
        id="wheat",
        names=CropNames(en="Wheat", hi="गेहूं", te="గోధుమ"),
        seasons=["rabi"],
        soil_types=["alluvial", "loam", "clay"],
        water_need="medium",
        regions=["irrigated", "upland"],
        cycle_days=125,
        growth_stages=[
            _stage("sowing", 0, "Sow into a fine, moist seedbed by mid-November for best yield."),
            _stage("tillering", 25, "Apply the first irrigation at crown-root stage (~21 days)."),
            _stage("flowering", 75, "Keep moisture steady at flowering; watch for rust."),
            _stage("grain_filling", 95, "Light irrigation helps grain fill; stop before harvest."),
            _stage("maturity", 115, "Harvest when grains are hard and straw turns golden."),
        ],
        susceptible_diseases=["leaf_rust", "stripe_rust", "loose_smut"],
    ),
    Crop(
        id="maize",
        names=CropNames(en="Maize", hi="मक्का", te="మొక్కజొన్న"),
        seasons=["kharif", "rabi"],
        soil_types=["red", "loam", "alluvial", "black"],
        water_need="medium",
        regions=["upland", "semi_arid", "coastal", "irrigated"],
        cycle_days=100,
        growth_stages=[
            _stage("germination", 0, "Sow in warm, well-drained soil; ensure even plant spacing."),
            _stage("vegetative", 20, "Weed early and top-dress nitrogen at knee-high stage."),
            _stage("tasseling", 50, "Most sensitive to water stress -- keep soil moist."),
            _stage("grain_filling", 70, "Maintain moisture for good cob fill; scout for fall armyworm."),
            _stage("maturity", 90, "Harvest when husks dry and kernels are hard."),
        ],
        susceptible_diseases=["turcicum_leaf_blight", "downy_mildew"],
    ),
    Crop(
        id="chilli",
        names=CropNames(en="Chilli", hi="मिर्च", te="మిర్చి"),
        seasons=["kharif", "rabi"],
        soil_types=["black", "red", "loam"],
        water_need="medium",
        regions=["semi_arid", "upland", "coastal"],
        cycle_days=150,
        growth_stages=[
            _stage("nursery", 0, "Raise seedlings in a protected nursery bed; guard against damping-off."),
            _stage("transplanting", 30, "Transplant 6-week seedlings; water in and provide light shade initially."),
            _stage("vegetative", 45, "Weed and stake; scout for thrips and mites that spread leaf curl."),
            _stage("flowering", 75, "Keep moisture steady to reduce flower drop."),
            _stage("fruiting", 100, "Harvest green or let ripen to red; pick regularly."),
        ],
        susceptible_diseases=["anthracnose", "leaf_curl_virus", "powdery_mildew"],
    ),
    Crop(
        id="sugarcane",
        names=CropNames(en="Sugarcane", hi="गन्ना", te="చెరకు"),
        seasons=["kharif"],
        soil_types=["alluvial", "black", "loam", "clay"],
        water_need="high",
        regions=["irrigated", "delta", "coastal"],
        cycle_days=330,
        growth_stages=[
            _stage("germination", 0, "Plant healthy setts in moist furrows; keep soil consistently damp."),
            _stage("tillering", 60, "Earth up and keep well irrigated to build strong tillers."),
            _stage("grand_growth", 150, "Peak water and nutrient demand -- do not let the crop dry."),
            _stage("maturity", 300, "Reduce irrigation to raise sugar; harvest at full maturity."),
        ],
        susceptible_diseases=["red_rot", "smut", "wilt"],
    ),
    Crop(
        id="onion",
        names=CropNames(en="Onion", hi="प्याज", te="ఉల్లిపాయ"),
        seasons=["rabi", "kharif"],
        soil_types=["red", "loam", "alluvial", "black"],
        water_need="medium",
        regions=["upland", "irrigated", "semi_arid"],
        cycle_days=130,
        growth_stages=[
            _stage("nursery", 0, "Raise seedlings in a raised bed; keep evenly moist."),
            _stage("transplanting", 40, "Transplant 6-7 week seedlings at close spacing."),
            _stage("bulb_development", 80, "Keep steady moisture; avoid nitrogen late as bulbs form."),
            _stage("maturity", 115, "Stop irrigation when tops fall over; cure bulbs before storage."),
        ],
        susceptible_diseases=["purple_blotch", "downy_mildew"],
    ),
    Crop(
        id="potato",
        names=CropNames(en="Potato", hi="आलू", te="బంగాళాదుంప"),
        seasons=["rabi"],
        soil_types=["loam", "sandy", "alluvial"],
        water_need="medium",
        regions=["upland", "irrigated", "hilly"],
        cycle_days=100,
        growth_stages=[
            _stage("sprouting", 0, "Plant well-sprouted seed tubers in loose, cool soil."),
            _stage("vegetative", 25, "Earth up ridges; keep weed-free and moist."),
            _stage("tuber_bulking", 50, "Steady moisture is critical now; scout for late blight in cool, wet spells."),
            _stage("maturity", 85, "Stop irrigation and let skins set before digging."),
        ],
        susceptible_diseases=["late_blight", "early_blight"],
    ),
    Crop(
        id="soybean",
        names=CropNames(en="Soybean", hi="सोयाबीन", te="సోయాబీన్"),
        seasons=["kharif"],
        soil_types=["black", "loam", "red"],
        water_need="medium",
        regions=["semi_arid", "upland"],
        cycle_days=100,
        growth_stages=[
            _stage("germination", 0, "Sow with monsoon onset into moist, well-drained soil."),
            _stage("vegetative", 20, "Keep weed-free in the first 40 days; avoid waterlogging."),
            _stage("flowering", 45, "Ensure moisture at flowering and pod set."),
            _stage("pod_filling", 65, "Steady moisture fills pods; scout for defoliators."),
            _stage("maturity", 90, "Harvest when leaves drop and pods rattle."),
        ],
        susceptible_diseases=["yellow_mosaic_virus", "rust"],
    ),
    Crop(
        id="mustard",
        names=CropNames(en="Mustard", hi="सरसों", te="ఆవాలు"),
        seasons=["rabi"],
        soil_types=["loam", "alluvial", "sandy"],
        water_need="low",
        regions=["irrigated", "semi_arid", "upland"],
        cycle_days=120,
        growth_stages=[
            _stage("sowing", 0, "Sow into a fine, moist seedbed in October-November."),
            _stage("vegetative", 25, "Thin to spacing; one irrigation at rosette stage helps."),
            _stage("flowering", 55, "Irrigate at flowering; scout for aphids."),
            _stage("pod_filling", 80, "Light irrigation aids seed fill."),
            _stage("maturity", 105, "Harvest when pods turn yellow-brown to avoid shattering."),
        ],
        susceptible_diseases=["alternaria_blight", "white_rust"],
    ),
    Crop(
        id="bajra",
        names=CropNames(en="Pearl Millet (Bajra)", hi="बाजरा", te="సజ్జలు"),
        seasons=["kharif"],
        soil_types=["sandy", "red", "loam"],
        water_need="low",
        regions=["arid", "semi_arid", "upland"],
        cycle_days=85,
        growth_stages=[
            _stage("germination", 0, "Sow in sandy soil with early monsoon showers."),
            _stage("vegetative", 20, "Thin the stand and weed once; very drought-hardy."),
            _stage("earhead", 45, "Some moisture at earhead emergence lifts yield."),
            _stage("maturity", 75, "Harvest when grains harden in the earheads."),
        ],
        susceptible_diseases=["downy_mildew", "ergot"],
    ),
    Crop(
        id="jowar",
        names=CropNames(en="Sorghum (Jowar)", hi="ज्वार", te="జొన్న"),
        seasons=["kharif", "rabi"],
        soil_types=["black", "red", "loam"],
        water_need="low",
        regions=["semi_arid", "arid", "upland"],
        cycle_days=110,
        growth_stages=[
            _stage("germination", 0, "Sow into moist soil; ensure a firm, even seedbed."),
            _stage("vegetative", 25, "Weed early; the crop tolerates dry spells well."),
            _stage("flowering", 55, "Moisture at flowering improves grain set."),
            _stage("maturity", 95, "Harvest at hard-dough stage; dry grain well."),
        ],
        susceptible_diseases=["grain_mold", "anthracnose"],
    ),
    Crop(
        id="ragi",
        names=CropNames(en="Finger Millet (Ragi)", hi="रागी", te="రాగులు"),
        seasons=["kharif"],
        soil_types=["red", "loam", "sandy"],
        water_need="low",
        regions=["upland", "semi_arid", "hilly"],
        cycle_days=115,
        growth_stages=[
            _stage("nursery", 0, "Raise seedlings or line-sow; keep the bed moist."),
            _stage("transplanting", 25, "Transplant into puddled or moist fields; weed early."),
            _stage("earhead", 60, "Light moisture at earhead stage aids fingers filling."),
            _stage("maturity", 100, "Harvest when earheads turn brown; thresh when dry."),
        ],
        susceptible_diseases=["blast"],
    ),
    Crop(
        id="green_gram",
        names=CropNames(en="Green Gram (Moong)", hi="मूंग", te="పెసలు"),
        seasons=["kharif", "zaid"],
        soil_types=["loam", "sandy", "red", "black"],
        water_need="low",
        regions=["semi_arid", "irrigated", "upland"],
        cycle_days=65,
        growth_stages=[
            _stage("germination", 0, "Sow into moist soil; a short-duration, soil-enriching pulse."),
            _stage("vegetative", 15, "Weed once early; avoid waterlogging."),
            _stage("flowering", 30, "One irrigation at flowering if dry."),
            _stage("maturity", 55, "Pick pods as they mature; harvest in 2-3 pickings."),
        ],
        susceptible_diseases=["yellow_mosaic_virus", "powdery_mildew"],
    ),
    Crop(
        id="black_gram",
        names=CropNames(en="Black Gram (Urad)", hi="उड़द", te="మినుములు"),
        seasons=["kharif", "rabi"],
        soil_types=["black", "loam", "clay"],
        water_need="low",
        regions=["semi_arid", "delta", "irrigated"],
        cycle_days=80,
        growth_stages=[
            _stage("germination", 0, "Sow into moist, well-drained soil; often grown as a rice-fallow pulse."),
            _stage("vegetative", 18, "Keep weed-free early; avoid standing water."),
            _stage("flowering", 35, "Moisture at flowering and pod set lifts yield."),
            _stage("maturity", 70, "Harvest as pods blacken; avoid shattering losses."),
        ],
        susceptible_diseases=["yellow_mosaic_virus", "leaf_crinkle_virus"],
    ),
    Crop(
        id="red_gram",
        names=CropNames(en="Pigeon Pea (Red Gram)", hi="अरहर", te="కంది"),
        seasons=["kharif"],
        soil_types=["black", "red", "loam"],
        water_need="low",
        regions=["semi_arid", "upland"],
        cycle_days=160,
        growth_stages=[
            _stage("germination", 0, "Sow with monsoon onset; a deep-rooted, drought-hardy pulse."),
            _stage("vegetative", 30, "Weed early; intercrops well with cereals."),
            _stage("flowering", 90, "Protect flowers from pod borer; moisture helps pod set."),
            _stage("pod_development", 120, "Scout for pod borer through pod fill."),
            _stage("maturity", 150, "Harvest when most pods dry and rattle."),
        ],
        susceptible_diseases=["fusarium_wilt", "sterility_mosaic"],
    ),
    Crop(
        id="chickpea",
        names=CropNames(en="Chickpea (Bengal Gram)", hi="चना", te="శనగలు"),
        seasons=["rabi"],
        soil_types=["black", "loam", "clay"],
        water_need="low",
        regions=["semi_arid", "upland", "irrigated"],
        cycle_days=110,
        growth_stages=[
            _stage("germination", 0, "Sow on residual moisture after the monsoon in October-November."),
            _stage("vegetative", 25, "Avoid heavy irrigation; the crop prefers cool, dry growth."),
            _stage("flowering", 55, "One irrigation at flowering if soil is dry; scout for pod borer."),
            _stage("pod_development", 75, "Protect pods from borer; light moisture aids fill."),
            _stage("maturity", 100, "Harvest when plants dry and pods turn brown."),
        ],
        susceptible_diseases=["fusarium_wilt", "ascochyta_blight"],
    ),
    Crop(
        id="banana",
        names=CropNames(en="Banana", hi="केला", te="అరటి"),
        seasons=["kharif", "rabi", "zaid"],
        soil_types=["alluvial", "loam", "red"],
        water_need="high",
        regions=["coastal", "delta", "irrigated"],
        cycle_days=330,
        growth_stages=[
            _stage("planting", 0, "Plant healthy tissue-culture or suckers in well-drained pits."),
            _stage("vegetative", 60, "Keep well irrigated and fed; remove excess suckers."),
            _stage("flowering", 210, "Support the bunch; maintain steady moisture."),
            _stage("fruit_development", 260, "Cover the bunch; harvest at three-quarter maturity."),
        ],
        susceptible_diseases=["panama_wilt", "sigatoka_leaf_spot", "bunchy_top_virus"],
    ),
    Crop(
        id="turmeric",
        names=CropNames(en="Turmeric", hi="हल्दी", te="పసుపు"),
        seasons=["kharif"],
        soil_types=["loam", "red", "alluvial"],
        water_need="high",
        regions=["coastal", "irrigated", "upland"],
        cycle_days=250,
        growth_stages=[
            _stage("sprouting", 0, "Plant healthy rhizomes in ridges with the monsoon; mulch well."),
            _stage("vegetative", 60, "Keep moist and weed-free; earth up periodically."),
            _stage("rhizome_development", 150, "Steady moisture builds rhizomes; do not let soil dry."),
            _stage("maturity", 220, "Stop irrigation as leaves yellow; harvest and cure rhizomes."),
        ],
        susceptible_diseases=["rhizome_rot", "leaf_spot"],
    ),
    Crop(
        id="brinjal",
        names=CropNames(en="Brinjal (Eggplant)", hi="बैंगन", te="వంకాయ"),
        seasons=["kharif", "rabi", "zaid"],
        soil_types=["loam", "red", "black", "alluvial"],
        water_need="medium",
        regions=["coastal", "upland", "irrigated"],
        cycle_days=140,
        growth_stages=[
            _stage("nursery", 0, "Raise seedlings in a protected bed; guard against damping-off."),
            _stage("transplanting", 30, "Transplant sturdy seedlings; water in well."),
            _stage("vegetative", 45, "Stake and weed; scout for shoot and fruit borer."),
            _stage("flowering", 70, "Keep moisture steady for continuous fruiting."),
            _stage("fruiting", 90, "Harvest glossy tender fruit regularly; remove borer-hit fruit."),
        ],
        susceptible_diseases=["bacterial_wilt", "little_leaf"],
    ),
    Crop(
        id="okra",
        names=CropNames(en="Okra (Bhindi)", hi="भिंडी", te="బెండకాయ"),
        seasons=["kharif", "zaid"],
        soil_types=["loam", "sandy", "red", "alluvial"],
        water_need="medium",
        regions=["coastal", "upland", "irrigated"],
        cycle_days=90,
        growth_stages=[
            _stage("germination", 0, "Sow directly into warm, moist soil; soak seed to speed germination."),
            _stage("vegetative", 20, "Weed early; scout for sucking pests spreading yellow vein mosaic."),
            _stage("flowering", 40, "Keep moisture steady as flowering begins."),
            _stage("fruiting", 50, "Pick tender pods every 2-3 days to keep plants bearing."),
        ],
        susceptible_diseases=["yellow_vein_mosaic_virus", "powdery_mildew"],
    ),
    Crop(
        id="sunflower",
        names=CropNames(en="Sunflower", hi="सूरजमुखी", te="ప్రొద్దుతిరుగుడు"),
        seasons=["rabi", "kharif", "zaid"],
        soil_types=["black", "loam", "red", "alluvial"],
        water_need="medium",
        regions=["semi_arid", "upland", "irrigated"],
        cycle_days=95,
        growth_stages=[
            _stage("germination", 0, "Sow into a moist, firm seedbed; ensure even spacing."),
            _stage("vegetative", 20, "Weed early; the crop is fairly drought-tolerant."),
            _stage("flowering", 45, "Most sensitive to water stress -- irrigate at flowering."),
            _stage("seed_filling", 65, "Steady moisture fills seeds; support in windy areas."),
            _stage("maturity", 85, "Harvest when the back of the head turns yellow-brown."),
        ],
        susceptible_diseases=["alternaria_leaf_spot", "downy_mildew"],
    ),
    Crop(
        id="sesame",
        names=CropNames(en="Sesame (Til)", hi="तिल", te="నువ్వులు"),
        seasons=["kharif", "zaid"],
        soil_types=["sandy", "loam", "red"],
        water_need="low",
        regions=["arid", "semi_arid", "coastal"],
        cycle_days=90,
        growth_stages=[
            _stage("germination", 0, "Sow shallow into warm, moist soil; a drought-hardy oilseed."),
            _stage("vegetative", 20, "Weed early; avoid waterlogging, which the crop dislikes."),
            _stage("flowering", 40, "Light moisture at flowering improves capsule set."),
            _stage("maturity", 80, "Harvest as capsules yellow; handle gently to avoid shattering."),
        ],
        susceptible_diseases=["phyllody", "leaf_spot"],
    ),
    Crop(
        id="castor",
        names=CropNames(en="Castor", hi="अरंडी", te="ఆముదం"),
        seasons=["kharif"],
        soil_types=["red", "sandy", "loam", "black"],
        water_need="low",
        regions=["semi_arid", "arid", "upland"],
        cycle_days=150,
        growth_stages=[
            _stage("germination", 0, "Sow into moist soil at the monsoon onset; a hardy oilseed."),
            _stage("vegetative", 30, "Weed early; the crop tolerates dry spells."),
            _stage("spike_formation", 70, "Moisture at spike formation improves capsule set."),
            _stage("maturity", 120, "Pick spikes in stages as capsules dry."),
        ],
        susceptible_diseases=["wilt", "gray_mold"],
    ),
    Crop(
        id="cabbage",
        names=CropNames(en="Cabbage", hi="पत्ता गोभी", te="క్యాబేజీ"),
        seasons=["rabi"],
        soil_types=["loam", "alluvial", "clay"],
        water_need="medium",
        regions=["upland", "irrigated", "hilly"],
        cycle_days=100,
        growth_stages=[
            _stage("nursery", 0, "Raise seedlings in a cool, protected bed."),
            _stage("transplanting", 30, "Transplant 4-5 week seedlings; water in well."),
            _stage("head_formation", 55, "Steady moisture and nitrogen build tight heads."),
            _stage("maturity", 90, "Harvest when heads are firm and solid."),
        ],
        susceptible_diseases=["black_rot", "downy_mildew"],
    ),
    Crop(
        id="cauliflower",
        names=CropNames(en="Cauliflower", hi="फूल गोभी", te="కాలీఫ్లవర్"),
        seasons=["rabi"],
        soil_types=["loam", "alluvial", "clay"],
        water_need="medium",
        regions=["upland", "irrigated", "hilly"],
        cycle_days=100,
        growth_stages=[
            _stage("nursery", 0, "Raise seedlings in a cool, protected bed; guard against damping-off."),
            _stage("transplanting", 30, "Transplant sturdy seedlings; keep evenly moist."),
            _stage("curd_formation", 55, "Steady moisture is critical; shade curds from direct sun."),
            _stage("maturity", 90, "Harvest when curds are compact and white."),
        ],
        susceptible_diseases=["black_rot", "downy_mildew"],
    ),
    Crop(
        id="watermelon",
        names=CropNames(en="Watermelon", hi="तरबूज", te="పుచ్చకాయ"),
        seasons=["zaid"],
        soil_types=["sandy", "loam", "alluvial"],
        water_need="medium",
        regions=["coastal", "irrigated", "arid"],
        cycle_days=90,
        growth_stages=[
            _stage("germination", 0, "Sow on warming soil along river beds or ridges; a summer vine crop."),
            _stage("vine_growth", 20, "Train vines and weed; keep moisture steady but avoid wetting crowns."),
            _stage("flowering", 40, "Ensure moisture and pollination at flowering."),
            _stage("fruit_development", 55, "Steady moisture swells fruit; reduce water near ripening for sweetness."),
            _stage("maturity", 80, "Harvest when the ground spot turns creamy and the tendril dries."),
        ],
        susceptible_diseases=["fusarium_wilt", "anthracnose"],
    ),
]


def seed() -> None:
    for crop in CROPS:
        doc_id = upsert_crop(crop)
        print(
            f"seeded crop '{doc_id}' ({crop.names.en}, {crop.cycle_days}d, "
            f"seasons={','.join(crop.seasons)}, diseases={','.join(crop.susceptible_diseases) or '-'})"
        )
    print(f"done: {len(CROPS)} crops")


if __name__ == "__main__":
    seed()
